server:
  port: 8080

spring:
  application:
    name: tt42-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: true

tt42-api:
  ribbon:
    ReadTimeout: 1500

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false # hystrix timeout MUST be disabled or configured longer than ribbon timeout
