spring:
  application:
    name: tt52-api-2

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: true

tt51-api-1:
  ribbon:
    ReadTimeout: 1500

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false # hystrix timeout MUST be disabled or configured longer than ribbon timeout
