server:
  port: 8081

spring:
  application:
    name: tt74-api-1
  sleuth:
    sampler:
      percentage: 0.5 # more likely to be sampled, default 0.1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
