spring:
  application:
    name: eureka-server

---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
